export const homeObjOne = {
    id: 'about',
    lightBg: false,
    lightText: true,
    lightTextDesc: true,
    topLine: 'Premium Bank',
    headline: 'Unlimited Transaction With zero fees',
    description: 'Get access to our exclusive app that allows you to send unlimited transactions without getting charges any fees',
    buttonLabel: 'Get Started',
    imgStart: false,
    img: require('../../images/svg-1.svg'),
    alt: 'Development',
    dark: true,
    primary: true,
    darkText: false,
};

export const homeObjTwo = {
    id: 'discover',
    lightBg: false,
    lightText: true,
    lightTextDesc: true,
    topLine: 'Unlimited Access',
    headline: 'Unlimited Transaction With zero fees',
    description: 'Get access to our exclusive app that allows you to send unlimited transactions without getting charges any fees',
    buttonLabel: 'Learn More',
    imgStart: true,
    img: require('../../images/svg-2.svg'),
    alt: 'Business',
    dark: true,
    primary: true,
    darkText: false,
};

export const homeObjThree = {
    id: 'services',
    lightBg: false,
    lightText: true,
    lightTextDesc: true,
    topLine: 'Premium Bank',
    headline: 'Unlimited Transaction With zero fees',
    description: 'Get access to our exclusive app that allows you to send unlimited transactions without getting charges any fees',
    buttonLabel: 'Get Started',
    imgStart: false,
    img: require('../../images/svg-3.svg'),
    alt: 'Digital Marketing',
    dark: true,
    primary: true,
    darkText: false,
};